name: Run Tests, Build protobufs for Python, TypeScript, and Go

on:
  push:
    branches:
      - 'main'
      - 'dev'
  pull_request:
    branches:
      - main     # Run on pull requests targeting the main branch
      - dev     # Run on pull requests targeting the dev branch

jobs:
  build_protos:
    # This job builds the protobufs for Python, TypeScript, and Go
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]  # Using Node.js version 22
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Update apt repositories
        run: |
          sudo add-apt-repository universe
          sudo apt-get update

      - name: Install protoc
        run: |
          sudo apt-get install -y protobuf-compiler

      - name: Build TypeScript protobufs
        run: |
          cd protobuf
          echo "Installing npm dependencies..."
          npm install || { echo "npm install failed"; exit 1; }
          echo "Compiling TypeScript protobufs..."
          npm run compile-ts || { echo "npm run compile-ts failed"; exit 1; }

      - name: Build Golang protobufs
        run: |
          cd protobuf
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          echo "Compiling Golang protobufs..."
      
      - name: Add Go bin to PATH
        run: echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Build Golang protobufs
        run: |
          npm run compile-go || { echo "npm run compile-go failed"; exit 1; }

      - name: Upload Protobuf Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: compiled-protos
          path: generated  # Path to the built files

  run_tests_ts:
    # This job runs tests for the Python, TypeScript, and Go code
    runs-on: ubuntu-latest
    needs: build_protos
    strategy:
      matrix:
        node-version: [22.x]  # Using Node.js version 22
    steps:
      - name: Download Protobuf Artifacts
        uses: actions/download-artifact@v3
        with:
          name: compiled-protos

      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run TypeScript tests
        run: |
          npm install @bufbuild/protobuf
          npm install tsconfig-paths
          echo "Current directory:"
          ls -l
          echo "Changing to tests/node directory..."
          cd tests/node
          echo "Installing npm dependencies..."
          npm install --include=dev || { echo "npm install --include=dev failed"; exit 1; }
          echo "Installing @bufbuild/protobuf..."
          echo "Running TypeScript tests..."
          npm run test

  # run_tests_go:
  #   # This job runs tests for the Python, TypeScript, and Go code
  #   runs-on: ubuntu-latest
  #   needs: build_protos
  #   strategy:
  #     matrix:
  #       go-version: [1.17]  # Using Go version 1.17
  #   steps:
  #     - name: Download Protobuf Artifacts
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: compiled-protos

  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Go
  #       uses: actions/setup-go@v2
  #       with:
  #         go-version: ${{ matrix.go-version }}

  #     - name: Run Go tests
  #       run: |
  #         echo "Current directory:"
  #         ls -l
  #         echo "Changing to tests/go directory..."
  #         cd tests/go
  #         echo "Running Go tests..."
  #         go test ./...

  build_npm:
    # This job builds the npm package
    runs-on: ubuntu-latest
    needs: [build_protos, run_tests_ts]
    if: github.ref == 'refs/heads/main'  # Only run on the main branch
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: |
          cd generated/typescript
          echo "Installing npm dependencies..."
          npm ci
          npm install --save
          npm run build
          git config user.email "brian@oof.gg"
          git config user.name "Brian S."
          echo "Bumping the version (choose one of patch, minor, or major)"
          NEW_VERSION=$(npm version patch -m "ci: bump version to %s")
          
          echo "Committing the new version and pushing to GitHub..."
          git add dist package.json package-lock.json
          git commit -m "ci: bump version to $NEW_VERSION"
          git push --follow-tags
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to npm
        run: |
          cd generated/typescript
          ls -l
          echo "Publishing to npm..."
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}