name: Run Tests, Build protobufs for Python, TypeScript, and Go

on:
  push:
    branches:
      - 'main'

jobs:
  build_protos:
    # This job builds the protobufs for Python, TypeScript, and Go
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]  # Using Node.js version 22
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Build TypeScript protobufs
        run: |
          cd protobuf
          echo "Installing npm dependencies..."
          npm install || { echo "npm install failed"; exit 1; }
          echo "Compiling TypeScript protobufs..."
          npm run compile-ts || { echo "npm run compile-ts failed"; exit 1; }

      - name: Upload Protobuf Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: compiled-protos
          path: generated  # Path to the built files

  run_tests:
    # This job runs tests for the Python, TypeScript, and Go code
    runs-on: ubuntu-latest
    needs: build_protos
    strategy:
      matrix:
        node-version: [22.x]  # Using Node.js version 22
    steps:
      - name: Download Protobuf Artifacts
        uses: actions/download-artifact@v3
        with:
          name: compiled-protos

      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run TypeScript tests
        run: |
          echo "Current directory:"
          ls -l
          echo "Changing to tests/node directory..."
          cd tests/node
          echo "Installing npm dependencies..."
          npm install --include=dev || { echo "npm install --include=dev failed"; exit 1; }
          echo "Installing @bufbuild/protobuf..."
          npm install @bufbuild/protobuf --save || { echo "npm install @bufbuild/protobuf failed"; exit 1; }
          echo "Current directory:"
          ls -l
          echo "Running TypeScript tests..."
          npm run test

# Install dependencies required for all jobs